### ISSUE TITLE
Project pictures don't scale properly in smartphone mode

### ISSUE THREAD

**Issue by MUWalter** [serg/yourfolio#10]
Hi Serg,

First of all, many thanks for your last commit, now the project images are perfectly inline if you add additional projects. But I realized another thing, when I updated the commits from 16 Nov 2020. It looks like the images don't scale in panorama mode anymore when you narrow the browser window or open it on a smartphone. I also tried a fresh install with the last yourfolio download with the standard pictures. It's the same.  Maybe you missed something when yo restructured the styles?

Kind regards,
Mark

**Comment by serg** [comment]
Hello Mark,

Nice to meet you and I am glad to help!
Also, thank you for your attention to this theme! It's very helpful for improving it.

Not sure if I understand you correctly.
Could you please send me a screenshot that describes this bug?
Also please add info about size of viewport on which you explore this issue. It will help me to reproduce this on my side.
You could get size of your viewport by using [this tool](https://themeslake.com/viewport/).

Thank you in advance!

**Comment by serg** [comment]
Did you mean a case like this when you rotate a screen?
<img width="875" alt="Screenshot 2021-04-29 at 13 45 11" src="https://user-images.githubusercontent.com/1274660/116539404-70eb8500-a8f1-11eb-8232-83e315f3db89.png">

**Comment by MUWalter** [comment]
No, I meant if you make the browser window smaller for example. In previous versions the pictures changed in landscape mode. Since the update from 16.11.2020 they don’t resize properly.

**Comment by MUWalter** [comment]
﻿Image0.png is the normal Browser view
Image1.png is before the update from 16.11.20 and
Image 2.png is from after the update from 16.11.20 where the pictures are not rendered in landscape mode anymore. 

Von meinem iPhone gesendet

**Comment by serg** [comment]
@MUWalter, seems like your images weren't uploaded.
Could you please upload this again?

**Comment by MUWalter** [comment]
@Serg I am sorry, I hope it works now:

screenshot 1 is the view with the normal browser width in both version of yourfolio, before the update from 16.11.2020 and after

https://user-images.githubusercontent.com/29971407/116775622-4cfc8080-aa64-11eb-90e5-696e857e2622.png

Before the update from 16.11.2020, the pictures are rendered in landscape mode when you make the browser window smaller or watch it on a smartphone (screenshot 2)

https://user-images.githubusercontent.com/29971407/116775648-70bfc680-aa64-11eb-987d-7c15bcb8ea5e.png

Screenshot 3 is how the pictures look like after the update from 16.11.2020 in the same browser size

https://user-images.githubusercontent.com/29971407/116775659-8df49500-aa64-11eb-99d8-8f7a0f33003b.png


All the best, 
Mark

**Comment by MUWalter** [comment]
@serg I update my last post, I hope you can see my screenshots now and understand what I mean.

**Comment by serg** [comment]
@MUWalter thank you for details!
It will help me with reproducing on my side
I will think about it and get back with results

**Comment by MUWalter** [comment]
Thank you very much, I am glad I could help!

**Comment by serg** [comment]
Hello Mark,
It was weird issue available only in Safari browser.
Now it fixed in [this commit](https://github.com/serg/yourfolio/commit/acaa8f1957e12fbd2ad872c2fcf0eaac3ed5c016) and pushed to `master` branch.

Please check and confirm if it works on your side.
Thanks!

**Comment by MUWalter** [comment]
Cool, so far it looks like it worked. Cheers!
