### ISSUE TITLE
More than 5 projects

### ISSUE THREAD

**Issue by MUWalter** [serg/yourfolio#9]
Hi @serg, I wanted to add another project to my website. So to try out the layout,I copied the first project entry and put it after the last project entry like this:

 - title: Strato
    type: wed design
    link: https://unsplash.com/photos/hpjSkU2UYSU
    image:
      url: works/strato.jpg
      alt: The Strato web design theme
      media: "(max-width: 46.25em)"
      params:
      - options: 1130x590
      - options: 848x443
      - options: 565x420
      - options: 360x318 Left
  - title: Analytik
    type: UI/UX
    link: https://unsplash.com/photos/yeB9jDmHm6M
    class: short-col
    image:
      url: works/analytik.jpg
      alt: The Analytic web design theme
      media: "(max-width: 46.25em)"
      params:
      - options: 364x590 Top
      - options: 848x443 Top
      - options: 565x420
      - options: 360x318
  - title: Friends
    type: Product Development
    link: https://unsplash.com/photos/ir5lIkVFqC4
    class: wide-col
    image:
      url: works/friends.jpg
      alt: The Friends theme
      media: "(max-width: 46.25em)"
      params:
      - options: 746x590 Left
      - options: 848x443 Top
      - options: 565x420 Left
      - options: 360x318 Center
  - title: Food
    type: web design
    link: https://unsplash.com/photos/JVSgcV8_vb4
    class: wide-col
    image:
      url: works/food.jpg
      alt: The Food website for recipes
      media: "(max-width: 46.25em)"
      params:
      - options: 746x590 Center
      - options: 848x443 Center
      - options: 565x420 Center
      - options: 360x318 Center
  - title: StatApp
    type: UI/UX
    link: https://unsplash.com/photos/nJX74kn1yn4
    class: short-col
    image:
      url: works/statapp.jpg
      alt: The application for statistic
      media: "(max-width: 46.25em)"
      params:
      - options: 364x590 Left
      - options: 848x443
      - options: 565x420 Center
      - options: 360x318 Center
      
 - title: Strato
    type: wed design
    link: https://unsplash.com/photos/hpjSkU2UYSU
    image:
      url: works/strato.jpg
      alt: The Strato web design theme
      media: "(max-width: 46.25em)"
      params:
      - options: 1130x590
      - options: 848x443
      - options: 565x420
      - options: 360x318 Left

The sixth project also appears on index.html, but unfortunately the picture is a little bit too small in regards to the other grouped pictures. Any idea how I can make it inline with the other 5 project pictures?

**Comment by serg** [comment]
@MUWalter Thank you for notify me about this issue!
I will try to look on this and resolve during couple days.

**Comment by MUWalter** [comment]
Great! Thanks...

**Comment by serg** [comment]
@MUWalter the gaps were fixed between project tiles. Now it should work as you expected.

Please pull latest code from current `master` branch or you could explore changes in [this commit](https://github.com/serg/yourfolio/commit/3d8956046b6e98bac0dc2d3325799fd123be7262).
The changes applied only for [app.scss](https://github.com/serg/yourfolio/blob/3d8956046b6e98bac0dc2d3325799fd123be7262/assets/scss/app.scss#L262-L278) file.

Thank you for let me know about this issue!
Have a great day!
